spring.application.name=agendamento

# Habilita o console do banco de dados no navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configura a URL do banco para ser fixa e não mudar a cada reinicialização
spring.datasource.url=jdbc:h2:mem:petshopdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
